
INSERT INTO genero(id,nombre) VALUES (1,'shoot em up');
INSERT INTO genero(id,nombre) VALUES (2,'videojuego de rol táctico');
INSERT INTO genero(id,nombre) VALUES (3,'videojuego de acción');
INSERT INTO genero(id,nombre) VALUES (4,'Videojuego de lucha');
INSERT INTO genero(id,nombre) VALUES (5,'acción-aventura');
INSERT INTO genero(id,nombre) VALUES (6,'videojuego de plataformas');
INSERT INTO genero(id,nombre) VALUES (7,'videojuego de carreras');
INSERT INTO genero(id,nombre) VALUES (8,'videojuego de estrategia por turnos');
INSERT INTO genero(id,nombre) VALUES (9,'videojuego de rol');
INSERT INTO genero(id,nombre) VALUES (10,'novela visual');
INSERT INTO genero(id,nombre) VALUES (11,'eroge');
INSERT INTO genero(id,nombre) VALUES (12,'survival horror');
INSERT INTO genero(id,nombre) VALUES (13,'videojuego de deportes');
INSERT INTO genero(id,nombre) VALUES (14,'videojuego de lógica');
INSERT INTO genero(id,nombre) VALUES (15,'videojuego de disparos en primera persona');
INSERT INTO genero(id,nombre) VALUES (16,'videojuego de estrategia en tiempo real');
INSERT INTO genero(id,nombre) VALUES (17,'videojuego de rol de acción');
INSERT INTO genero(id,nombre) VALUES (18,'mundo abierto');
INSERT INTO genero(id,nombre) VALUES (19,'videojuego de disparos');
INSERT INTO genero(id,nombre) VALUES (20,'juego de socialización');
INSERT INTO genero(id,nombre) VALUES (21,'videojuego de construcción de ciudades');
INSERT INTO genero(id,nombre) VALUES (22,'entretenimiento educativo');
INSERT INTO genero(id,nombre) VALUES (23,'videojuego de estrategia');
INSERT INTO genero(id,nombre) VALUES (24,'Proyección isométrica');
INSERT INTO genero(id,nombre) VALUES (25,'videojuego de disparos en tercera persona');
INSERT INTO genero(id,nombre) VALUES (26,'Videojuego activo');
INSERT INTO genero(id,nombre) VALUES (27,'videojuego de aventura');
INSERT INTO genero(id,nombre) VALUES (28,'Anime y manga escolares');
INSERT INTO genero(id,nombre) VALUES (29,'videojuego tradicional');
INSERT INTO genero(id,nombre) VALUES (30,'administración');
INSERT INTO genero(id,nombre) VALUES (31,'videojuego de simulación de vida');
INSERT INTO genero(id,nombre) VALUES (32,'videojuego de música');
INSERT INTO genero(id,nombre) VALUES (33,'fantasía');
INSERT INTO genero(id,nombre) VALUES (34,'videojuego de rol multijugador masivo en línea');
INSERT INTO genero(id,nombre) VALUES (35,'Beat ''em up');
INSERT INTO genero(id,nombre) VALUES (36,'simulador de embarcaciones');
INSERT INTO genero(id,nombre) VALUES (37,'golf');
INSERT INTO genero(id,nombre) VALUES (38,'deporte');
INSERT INTO genero(id,nombre) VALUES (39,'videojuego multijugador masivo en línea');
INSERT INTO genero(id,nombre) VALUES (40,'crossover ficcional');
INSERT INTO genero(id,nombre) VALUES (41,'Videojuego de construcción y gestión');
INSERT INTO genero(id,nombre) VALUES (42,'videojuego de simulación económica');
INSERT INTO genero(id,nombre) VALUES (43,'Danmaku');
INSERT INTO genero(id,nombre) VALUES (44,'simulador de vuelo');
INSERT INTO genero(id,nombre) VALUES (45,'Arcade');
INSERT INTO genero(id,nombre) VALUES (46,'Videojuego de disparos táctico');
INSERT INTO genero(id,nombre) VALUES (47,'Ecchi');
INSERT INTO genero(id,nombre) VALUES (48,'Harem');
INSERT INTO genero(id,nombre) VALUES (49,'manga y anime romántico');
INSERT INTO genero(id,nombre) VALUES (50,'juego de guerra');
INSERT INTO genero(id,nombre) VALUES (51,'jeu de grande stratégie');
INSERT INTO genero(id,nombre) VALUES (52,'Jeu historique');
INSERT INTO genero(id,nombre) VALUES (53,'aventura gráfica');
INSERT INTO genero(id,nombre) VALUES (54,'juego educativo');
INSERT INTO genero(id,nombre) VALUES (55,'videojuego de simulación');
INSERT INTO genero(id,nombre) VALUES (56,'novela de ciencia ficción');
INSERT INTO genero(id,nombre) VALUES (57,'Sim racing');
INSERT INTO genero(id,nombre) VALUES (58,'Tower defense');
INSERT INTO genero(id,nombre) VALUES (59,'mundo virtual');
INSERT INTO genero(id,nombre) VALUES (60,'videojuego de simulación de dios');
INSERT INTO genero(id,nombre) VALUES (61,'videojuego de construcción de imperios');
INSERT INTO genero(id,nombre) VALUES (62,'manga y anime dramático');
INSERT INTO genero(id,nombre) VALUES (63,'juego de rol');
INSERT INTO genero(id,nombre) VALUES (64,'primera persona');
INSERT INTO genero(id,nombre) VALUES (65,'videojuego de simulación de vehículos');
INSERT INTO genero(id,nombre) VALUES (66,'historieta');
INSERT INTO genero(id,nombre) VALUES (67,'película interactiva');
INSERT INTO genero(id,nombre) VALUES (68,'Videojuego de sigilo');
INSERT INTO genero(id,nombre) VALUES (69,'Videojuego de táctica en tiempo real');
INSERT INTO genero(id,nombre) VALUES (70,'Hack and slash');
INSERT INTO genero(id,nombre) VALUES (71,'pinball');
INSERT INTO genero(id,nombre) VALUES (72,'tahová taktická hra');
INSERT INTO genero(id,nombre) VALUES (73,'liste chronologique des jeux de labyrinthe');
INSERT INTO genero(id,nombre) VALUES (74,'juego de estrategia');
INSERT INTO genero(id,nombre) VALUES (75,'Videojuego de simulación de citas');
INSERT INTO genero(id,nombre) VALUES (76,'ciencia ficción');
INSERT INTO genero(id,nombre) VALUES (77,'videojuego de simulación espacial');
INSERT INTO genero(id,nombre) VALUES (78,'simulador de vuelo de combate');
INSERT INTO genero(id,nombre) VALUES (79,'Seinen');
INSERT INTO genero(id,nombre) VALUES (80,'anime y manga de comedia');
INSERT INTO genero(id,nombre) VALUES (81,'Videojuego de combate en vehículos');
INSERT INTO genero(id,nombre) VALUES (82,'foro');
INSERT INTO genero(id,nombre) VALUES (83,'Computación gráfica 2D');
INSERT INTO genero(id,nombre) VALUES (84,'neo-noir');
INSERT INTO genero(id,nombre) VALUES (85,'List of party video games');
INSERT INTO genero(id,nombre) VALUES (86,'Juego de mazmorras');
INSERT INTO genero(id,nombre) VALUES (87,'video');
INSERT INTO genero(id,nombre) VALUES (88,'amor romántico');
INSERT INTO genero(id,nombre) VALUES (89,'aventura');
INSERT INTO genero(id,nombre) VALUES (90,'juego de cartas coleccionables');
INSERT INTO genero(id,nombre) VALUES (91,'simulación espacial');
INSERT INTO genero(id,nombre) VALUES (92,'Point-and-Click-Adventure');
INSERT INTO genero(id,nombre) VALUES (93,'Juego de ritmo');
INSERT INTO genero(id,nombre) VALUES (94,'videojuego de guerra');
INSERT INTO genero(id,nombre) VALUES (95,'Time management');
INSERT INTO genero(id,nombre) VALUES (96,'El sexo y la desnudez en los videojuegos');
INSERT INTO genero(id,nombre) VALUES (97,'mecha');
INSERT INTO genero(id,nombre) VALUES (98,'Roguelike');
INSERT INTO genero(id,nombre) VALUES (99,'lucha libre profesional');
INSERT INTO genero(id,nombre) VALUES (100,'videojuego bish�?jo');
INSERT INTO genero(id,nombre) VALUES (101,'Yuri');
INSERT INTO genero(id,nombre) VALUES (102,'videojuego social');
INSERT INTO genero(id,nombre) VALUES (103,'lucha');
INSERT INTO genero(id,nombre) VALUES (104,'interpretación de roles');
INSERT INTO genero(id,nombre) VALUES (105,'Offre groupée');
INSERT INTO genero(id,nombre) VALUES (106,'Turf');
INSERT INTO genero(id,nombre) VALUES (107,'aventura conversacional');
INSERT INTO genero(id,nombre) VALUES (108,'terror psicológico');
INSERT INTO genero(id,nombre) VALUES (109,'juego de simulación');
INSERT INTO genero(id,nombre) VALUES (110,'Simulace tanků');
INSERT INTO genero(id,nombre) VALUES (111,'Multiplayer online battle arena');
INSERT INTO genero(id,nombre) VALUES (112,'Clic');
INSERT INTO genero(id,nombre) VALUES (113,'un jugador');
INSERT INTO genero(id,nombre) VALUES (114,'Seznam po�?íta�?ových her');
INSERT INTO genero(id,nombre) VALUES (115,'Mah�? sh�?jo');
INSERT INTO genero(id,nombre) VALUES (116,'juego de naipes');
INSERT INTO genero(id,nombre) VALUES (117,'jeu de labyrinthe');
INSERT INTO genero(id,nombre) VALUES (118,'videojuego educativo');
INSERT INTO genero(id,nombre) VALUES (119,'juego de tablero');
INSERT INTO genero(id,nombre) VALUES (120,'automovilismo');
INSERT INTO genero(id,nombre) VALUES (121,'simulateur de vol');
INSERT INTO genero(id,nombre) VALUES (122,'skateboarding');
INSERT INTO genero(id,nombre) VALUES (123,'alta fantasía');
INSERT INTO genero(id,nombre) VALUES (124,'fútbol');
INSERT INTO genero(id,nombre) VALUES (125,'Juego de estilo alemán');
INSERT INTO genero(id,nombre) VALUES (126,'Rail shooter');
INSERT INTO genero(id,nombre) VALUES (127,'thriller psicológico');
INSERT INTO genero(id,nombre) VALUES (128,'Massive Multiplayer Online First-Person Shooter');
INSERT INTO genero(id,nombre) VALUES (129,'Γ�?αφικά βιντεοπαιχνιδιο�?');
INSERT INTO genero(id,nombre) VALUES (130,'Realidad aumentada');
INSERT INTO genero(id,nombre) VALUES (131,'jeu vidéo à défilement horizontal');
INSERT INTO genero(id,nombre) VALUES (132,'Guerra aérea');
INSERT INTO genero(id,nombre) VALUES (133,'Capturar la bandera');
INSERT INTO genero(id,nombre) VALUES (134,'Categoría:Videojuegos de aventura');
INSERT INTO genero(id,nombre) VALUES (135,'Juego de ingenio y lógica');
INSERT INTO genero(id,nombre) VALUES (136,'outil de création de jeux');
INSERT INTO genero(id,nombre) VALUES (137,'Minijuego');
INSERT INTO genero(id,nombre) VALUES (138,'sh�?nen');
INSERT INTO genero(id,nombre) VALUES (139,'ciberpunk');
INSERT INTO genero(id,nombre) VALUES (140,'dungeon crawler');
INSERT INTO genero(id,nombre) VALUES (141,'Mascota virtual');
INSERT INTO genero(id,nombre) VALUES (142,'simulador de submarinos');
INSERT INTO genero(id,nombre) VALUES (143,'Supervivencia, Aventura y Sandbox');
INSERT INTO genero(id,nombre) VALUES (144,'videojuego de artillería');
INSERT INTO genero(id,nombre) VALUES (145,'Q8018176');
INSERT INTO genero(id,nombre) VALUES (146,'Snooker');
INSERT INTO genero(id,nombre) VALUES (147,'pool');
INSERT INTO genero(id,nombre) VALUES (148,'danza');
INSERT INTO genero(id,nombre) VALUES (149,'Light gun shooter');
INSERT INTO genero(id,nombre) VALUES (150,'simulador de trenes');
INSERT INTO genero(id,nombre) VALUES (151,'Vida artificial');
INSERT INTO genero(id,nombre) VALUES (152,'deporte extremo');
INSERT INTO genero(id,nombre) VALUES (153,'art game');
INSERT INTO genero(id,nombre) VALUES (154,'Emergent gameplay');
INSERT INTO genero(id,nombre) VALUES (155,'simulateur');
INSERT INTO genero(id,nombre) VALUES (156,'combate');
INSERT INTO genero(id,nombre) VALUES (157,'Pachinko');
INSERT INTO genero(id,nombre) VALUES (158,'jugador contra jugador');
INSERT INTO genero(id,nombre) VALUES (159,'juegos tradicionales');
INSERT INTO genero(id,nombre) VALUES (160,'baloncesto');
INSERT INTO genero(id,nombre) VALUES (161,'fútbol americano');
INSERT INTO genero(id,nombre) VALUES (162,'tenis');
INSERT INTO genero(id,nombre) VALUES (163,'Karaoke');
INSERT INTO genero(id,nombre) VALUES (164,'fiesta');
INSERT INTO genero(id,nombre) VALUES (165,'Wirtschaftssimulation');
INSERT INTO genero(id,nombre) VALUES (166,'Turns, rounds and time-keeping systems in games');
INSERT INTO genero(id,nombre) VALUES (167,'Bankvorteil');
INSERT INTO genero(id,nombre) VALUES (168,'militar');
INSERT INTO genero(id,nombre) VALUES (169,'satélite artificial');
INSERT INTO genero(id,nombre) VALUES (170,'Videojuego social');
INSERT INTO genero(id,nombre) VALUES (171,'billar');
INSERT INTO genero(id,nombre) VALUES (172,'Dungeon Crawl');
INSERT INTO genero(id,nombre) VALUES (173,'Desarrollo de videojuegos independiente');
INSERT INTO genero(id,nombre) VALUES (174,'Formel 1-løb');
INSERT INTO genero(id,nombre) VALUES (175,'hockey sobre hielo');
INSERT INTO genero(id,nombre) VALUES (176,'ficción post-apocalíptica');
INSERT INTO genero(id,nombre) VALUES (177,'literatura de terror');
INSERT INTO genero(id,nombre) VALUES (178,'simulador de camiones');
INSERT INTO genero(id,nombre) VALUES (179,'Laberinto');
INSERT INTO genero(id,nombre) VALUES (180,'anime y manga de terror');
INSERT INTO genero(id,nombre) VALUES (181,'construcción');
INSERT INTO genero(id,nombre) VALUES (182,'Videojuego no lineal');
INSERT INTO genero(id,nombre) VALUES (183,'multijugador');
INSERT INTO genero(id,nombre) VALUES (184,'acción');
INSERT INTO genero(id,nombre) VALUES (185,'Cracker');
INSERT INTO genero(id,nombre) VALUES (186,'Editor de niveles');
INSERT INTO genero(id,nombre) VALUES (187,'jeu de puzzle');
INSERT INTO genero(id,nombre) VALUES (188,'arkádní videohra');
INSERT INTO genero(id,nombre) VALUES (189,'Videojuego de simulación social');
INSERT INTO genero(id,nombre) VALUES (190,'mech simulator');
INSERT INTO genero(id,nombre) VALUES (191,'List of artificial pet games');
INSERT INTO genero(id,nombre) VALUES (192,'Monomito');
INSERT INTO genero(id,nombre) VALUES (193,'Non-Game');
INSERT INTO genero(id,nombre) VALUES (194,'Game Art');
INSERT INTO genero(id,nombre) VALUES (195,'Fantasía medieval');
INSERT INTO genero(id,nombre) VALUES (196,'shooter sobre raíles');
INSERT INTO genero(id,nombre) VALUES (197,'endless video game');
INSERT INTO genero(id,nombre) VALUES (198,'Jump scare');
INSERT INTO genero(id,nombre) VALUES (199,'programa de concurso');
INSERT INTO genero(id,nombre) VALUES (200,'misterio');
INSERT INTO genero(id,nombre) VALUES (201,'Tile-matching video game');
INSERT INTO genero(id,nombre) VALUES (202,'videojuego de simulación política');
INSERT INTO genero(id,nombre) VALUES (203,'compilación de videojuegos');
INSERT INTO genero(id,nombre) VALUES (204,'traducción automática');
INSERT INTO genero(id,nombre) VALUES (205,'Videojuego de navegador');
INSERT INTO genero(id,nombre) VALUES (206,'Metroidvania');
INSERT INTO genero(id,nombre) VALUES (207,'Casse-briques');
INSERT INTO genero(id,nombre) VALUES (208,'historia');
INSERT INTO genero(id,nombre) VALUES (209,'Videojuego casual');
INSERT INTO genero(id,nombre) VALUES (210,'Cross-genre');
INSERT INTO genero(id,nombre) VALUES (211,'Puzzled');
INSERT INTO genero(id,nombre) VALUES (212,'arte');
INSERT INTO genero(id,nombre) VALUES (213,'suspenso');
INSERT INTO genero(id,nombre) VALUES (214,'coming-of-age');
INSERT INTO genero(id,nombre) VALUES (215,'ficción sobrenatural');
INSERT INTO genero(id,nombre) VALUES (216,'Videojuego independiente');
INSERT INTO genero(id,nombre) VALUES (217,'cine B');
INSERT INTO genero(id,nombre) VALUES (218,'Gráficos 3D por computadora');
INSERT INTO genero(id,nombre) VALUES (219,'Breakout');
INSERT INTO genero(id,nombre) VALUES (220,'pesca');
INSERT INTO genero(id,nombre) VALUES (221,'ciencia ficción militar');
INSERT INTO genero(id,nombre) VALUES (222,'cine de aventuras');
INSERT INTO genero(id,nombre) VALUES (223,'tactical wargame');
INSERT INTO genero(id,nombre) VALUES (224,'boxeo');
INSERT INTO genero(id,nombre) VALUES (225,'Free-to-play');
INSERT INTO genero(id,nombre) VALUES (226,'cine romántico');
INSERT INTO genero(id,nombre) VALUES (227,'novela');
INSERT INTO genero(id,nombre) VALUES (228,'comedia');
INSERT INTO genero(id,nombre) VALUES (229,'historieta de ciencia ficción');
INSERT INTO genero(id,nombre) VALUES (230,'Physik-Spiel');
INSERT INTO genero(id,nombre) VALUES (231,'artillería');
INSERT INTO genero(id,nombre) VALUES (232,'Super Scope');
INSERT INTO genero(id,nombre) VALUES (233,'Solitario de cartas');
INSERT INTO genero(id,nombre) VALUES (234,'Christian video game');
INSERT INTO genero(id,nombre) VALUES (235,'Olympic video games');
INSERT INTO genero(id,nombre) VALUES (236,'Command & Conquer');
INSERT INTO genero(id,nombre) VALUES (237,'Beat ''Em Up');
INSERT INTO genero(id,nombre) VALUES (238,'Targeting');
INSERT INTO genero(id,nombre) VALUES (239,'carrera');
INSERT INTO genero(id,nombre) VALUES (240,'estadio cubierto');
INSERT INTO genero(id,nombre) VALUES (241,'béisbol');
INSERT INTO genero(id,nombre) VALUES (242,'pistola de luz');
INSERT INTO genero(id,nombre) VALUES (243,'cine de acción');
INSERT INTO genero(id,nombre) VALUES (244,'Ajedrez por computadora');
INSERT INTO genero(id,nombre) VALUES (245,'videojuego en línea');
INSERT INTO genero(id,nombre) VALUES (246,'Fórmula 1');
INSERT INTO genero(id,nombre) VALUES (247,'Trivia');
INSERT INTO genero(id,nombre) VALUES (248,'off-road racing');
INSERT INTO genero(id,nombre) VALUES (249,'Pong');
INSERT INTO genero(id,nombre) VALUES (250,'bowling');
INSERT INTO genero(id,nombre) VALUES (251,'álbum recopilatorio');
INSERT INTO genero(id,nombre) VALUES (252,'superhéroe');
INSERT INTO genero(id,nombre) VALUES (253,'esquí');
INSERT INTO genero(id,nombre) VALUES (254,'Reversi');
INSERT INTO genero(id,nombre) VALUES (255,'multijugador en línea');
INSERT INTO genero(id,nombre) VALUES (256,'BASIC');
INSERT INTO genero(id,nombre) VALUES (257,'quiz');
INSERT INTO genero(id,nombre) VALUES (258,'Guerra naval');
INSERT INTO genero(id,nombre) VALUES (259,'ritmo');
INSERT INTO genero(id,nombre) VALUES (260,'mahjong');
INSERT INTO genero(id,nombre) VALUES (261,'�?يلم عيد الميلاد');
INSERT INTO genero(id,nombre) VALUES (262,'ajedrez');
INSERT INTO genero(id,nombre) VALUES (263,'Catégorie:Jeu vidéo de mecha');
INSERT INTO genero(id,nombre) VALUES (264,'space opera');
INSERT INTO genero(id,nombre) VALUES (265,'videojuegos sobre futbol');
INSERT INTO genero(id,nombre) VALUES (266,'cuatrimoto');
INSERT INTO genero(id,nombre) VALUES (267,'Primera Guerra Mundial');
INSERT INTO genero(id,nombre) VALUES (268,'Videojuego de texto');
INSERT INTO genero(id,nombre) VALUES (269,'caza');
INSERT INTO genero(id,nombre) VALUES (270,'Deportes de fantasía');
INSERT INTO genero(id,nombre) VALUES (271,'juego de palabras');
INSERT INTO genero(id,nombre) VALUES (272,'música');
INSERT INTO genero(id,nombre) VALUES (273,'Character editor');
INSERT INTO genero(id,nombre) VALUES (274,'Family game');
INSERT INTO genero(id,nombre) VALUES (275,'Snowboarding video game');
INSERT INTO genero(id,nombre) VALUES (276,'Audiojuego');
INSERT INTO genero(id,nombre) VALUES (277,'Space Invaders');
INSERT INTO genero(id,nombre) VALUES (278,'voleibol de playa');
INSERT INTO genero(id,nombre) VALUES (279,'novela fantástica');
INSERT INTO genero(id,nombre) VALUES (280,'película infantil');
INSERT INTO genero(id,nombre) VALUES (281,'Minigolf');
INSERT INTO genero(id,nombre) VALUES (282,'espada y brujería');
INSERT INTO genero(id,nombre) VALUES (283,'Juegos psicológicos');
INSERT INTO genero(id,nombre) VALUES (284,'Dancing');
INSERT INTO genero(id,nombre) VALUES (285,'Póquer');
INSERT INTO genero(id,nombre) VALUES (286,'Aeróbic');
INSERT INTO genero(id,nombre) VALUES (287,'simulateur de conduite');
INSERT INTO genero(id,nombre) VALUES (288,'sh�?jo');
INSERT INTO genero(id,nombre) VALUES (289,'surrealismo');
INSERT INTO genero(id,nombre) VALUES (290,'sports manager');
INSERT INTO genero(id,nombre) VALUES (291,'Space Combat');
INSERT INTO genero(id,nombre) VALUES (292,'arte interactivo');
INSERT INTO genero(id,nombre) VALUES (293,'Juego serio');
INSERT INTO genero(id,nombre) VALUES (294,'Memorama');
INSERT INTO genero(id,nombre) VALUES (295,'MUD');
INSERT INTO genero(id,nombre) VALUES (296,'fantasía oscura');
INSERT INTO genero(id,nombre) VALUES (297,'Boliche');
INSERT INTO genero(id,nombre) VALUES (298,'low fantasy');
INSERT INTO genero(id,nombre) VALUES (299,'críquet');
INSERT INTO genero(id,nombre) VALUES (300,'Justa');
INSERT INTO genero(id,nombre) VALUES (301,'Vendimia');
INSERT INTO genero(id,nombre) VALUES (302,'RPG');
INSERT INTO genero(id,nombre) VALUES (303,'Videojuego de estrategia en tiempo real multijugador masivo en línea');
INSERT INTO genero(id,nombre) VALUES (304,'Matching game');
INSERT INTO genero(id,nombre) VALUES (305,'juegos de apuestas');
INSERT INTO genero(id,nombre) VALUES (306,'educación');
INSERT INTO genero(id,nombre) VALUES (307,'Segunda Guerra Mundial');
INSERT INTO genero(id,nombre) VALUES (308,'novela romántica');
INSERT INTO genero(id,nombre) VALUES (309,'snowboarding');
INSERT INTO genero(id,nombre) VALUES (310,'Global warming game');
INSERT INTO genero(id,nombre) VALUES (311,'editor de gráficos rasterizados');
INSERT INTO genero(id,nombre) VALUES (312,'Lectura rápida');
INSERT INTO genero(id,nombre) VALUES (313,'Arts du langage');
INSERT INTO genero(id,nombre) VALUES (314,'تسطير');
INSERT INTO genero(id,nombre) VALUES (315,'Guide officiel de jeu vidéo');
INSERT INTO genero(id,nombre) VALUES (316,'Jeu vidéo Otome');
INSERT INTO genero(id,nombre) VALUES (317,'Sinistar');
INSERT INTO genero(id,nombre) VALUES (318,'Sh�?gi');
INSERT INTO genero(id,nombre) VALUES (319,'artes marciales mixtas');
INSERT INTO genero(id,nombre) VALUES (320,'Pub games');
INSERT INTO genero(id,nombre) VALUES (321,'Air Combat');
INSERT INTO genero(id,nombre) VALUES (322,'Gran Turismo');
INSERT INTO genero(id,nombre) VALUES (323,'تصني�?:ألعاب سقوط القطع الأحجية');
INSERT INTO genero(id,nombre) VALUES (324,'heavy metal');
INSERT INTO genero(id,nombre) VALUES (325,'List of video games based on anime or manga');
INSERT INTO genero(id,nombre) VALUES (326,'MUSH');
INSERT INTO genero(id,nombre) VALUES (327,'Demo');
INSERT INTO genero(id,nombre) VALUES (328,'expansión');
INSERT INTO genero(id,nombre) VALUES (329,'Ciencia ciudadana');
INSERT INTO genero(id,nombre) VALUES (330,'Game with a purpose');
INSERT INTO genero(id,nombre) VALUES (331,'Cartouche multi-jeux');
INSERT INTO genero(id,nombre) VALUES (332,'hacer trampas');
INSERT INTO genero(id,nombre) VALUES (333,'juego de realidad alternativa');
INSERT INTO genero(id,nombre) VALUES (334,'noticia');
INSERT INTO genero(id,nombre) VALUES (335,'salto ecuestre');
INSERT INTO genero(id,nombre) VALUES (336,'guerra');
INSERT INTO genero(id,nombre) VALUES (337,'sátira');
INSERT INTO genero(id,nombre) VALUES (338,'mensajería instantánea');
INSERT INTO genero(id,nombre) VALUES (339,'diseño');
INSERT INTO genero(id,nombre) VALUES (340,'habilidad');
INSERT INTO genero(id,nombre) VALUES (341,'fotografía');
INSERT INTO genero(id,nombre) VALUES (342,'parodia');
INSERT INTO genero(id,nombre) VALUES (343,'Tiro skeet');
INSERT INTO genero(id,nombre) VALUES (344,'novela gráfica');
INSERT INTO genero(id,nombre) VALUES (345,'Carrera de destrucción');
INSERT INTO genero(id,nombre) VALUES (346,'juego abstracto');
INSERT INTO genero(id,nombre) VALUES (347,'Categoría:Compilaciones de videojuegos');
INSERT INTO genero(id,nombre) VALUES (348,'simulador de motocicletas');
INSERT INTO genero(id,nombre) VALUES (349,'jeu de course');
INSERT INTO genero(id,nombre) VALUES (350,'Categoría:Videojuegos de pinball');
INSERT INTO genero(id,nombre) VALUES (351,'software educativo');
INSERT INTO genero(id,nombre) VALUES (352,'futuro');
INSERT INTO genero(id,nombre) VALUES (353,'enciclopedia');
INSERT INTO genero(id,nombre) VALUES (354,'Jeu vidéo épisodique');
INSERT INTO genero(id,nombre) VALUES (355,'Productividad');
INSERT INTO genero(id,nombre) VALUES (356,'cocción');
INSERT INTO genero(id,nombre) VALUES (357,'rally');
INSERT INTO genero(id,nombre) VALUES (358,'ficción histórica');
INSERT INTO genero(id,nombre) VALUES (359,'science fiction video game');
INSERT INTO genero(id,nombre) VALUES (360,'Isometrische Perspektive in Computerspielen');
INSERT INTO genero(id,nombre) VALUES (361,'quidditch');
INSERT INTO genero(id,nombre) VALUES (362,'cine dramático');
INSERT INTO genero(id,nombre) VALUES (363,'robinsonade');
INSERT INTO genero(id,nombre) VALUES (364,'bidimensional');
INSERT INTO genero(id,nombre) VALUES (365,'Making-of');