INSERT INTO plataforma(id,nombre) VALUES (1,'Sinclair ZX Spectrum');
INSERT INTO plataforma(id,nombre) VALUES (2,'Commodore 64');
INSERT INTO plataforma(id,nombre) VALUES (3,'Commodore Amiga');
INSERT INTO plataforma(id,nombre) VALUES (4,'DOS');
INSERT INTO plataforma(id,nombre) VALUES (5,'Amstrad CPC');
INSERT INTO plataforma(id,nombre) VALUES (6,'Atari ST');
INSERT INTO plataforma(id,nombre) VALUES (7,'MSX');
INSERT INTO plataforma(id,nombre) VALUES (8,'PlayStation Portable');
INSERT INTO plataforma(id,nombre) VALUES (9,'Game Boy Advance');
INSERT INTO plataforma(id,nombre) VALUES (10,'Super Nintendo Entertainment System');
INSERT INTO plataforma(id,nombre) VALUES (11,'Mega Drive');
INSERT INTO plataforma(id,nombre) VALUES (12,'Acorn Archimedes');
INSERT INTO plataforma(id,nombre) VALUES (13,'Mac OS');
INSERT INTO plataforma(id,nombre) VALUES (14,'iOS');
INSERT INTO plataforma(id,nombre) VALUES (15,'3DO Interactive Multiplayer');
INSERT INTO plataforma(id,nombre) VALUES (16,'CD-i');
INSERT INTO plataforma(id,nombre) VALUES (17,'Microsoft Windows');
INSERT INTO plataforma(id,nombre) VALUES (18,'Wii');
INSERT INTO plataforma(id,nombre) VALUES (19,'PlayStation 2');
INSERT INTO plataforma(id,nombre) VALUES (20,'Nintendo DS');
INSERT INTO plataforma(id,nombre) VALUES (21,'WonderSwan Color');
INSERT INTO plataforma(id,nombre) VALUES (22,'Nintendo Entertainment System');
INSERT INTO plataforma(id,nombre) VALUES (23,'Android');
INSERT INTO plataforma(id,nombre) VALUES (24,'Linux');
INSERT INTO plataforma(id,nombre) VALUES (25,'macOS');
INSERT INTO plataforma(id,nombre) VALUES (26,'Atari 2600');
INSERT INTO plataforma(id,nombre) VALUES (27,'Atari 7800');
INSERT INTO plataforma(id,nombre) VALUES (28,'PlayStation 3');
INSERT INTO plataforma(id,nombre) VALUES (29,'Xbox 360');
INSERT INTO plataforma(id,nombre) VALUES (30,'Apple II');
INSERT INTO plataforma(id,nombre) VALUES (31,'PlayStation 4');
INSERT INTO plataforma(id,nombre) VALUES (32,'Arcade');
INSERT INTO plataforma(id,nombre) VALUES (33,'Wii U');
INSERT INTO plataforma(id,nombre) VALUES (34,'Famicom Disk System');
INSERT INTO plataforma(id,nombre) VALUES (35,'PlayStation Vita');
INSERT INTO plataforma(id,nombre) VALUES (36,'Xbox');
INSERT INTO plataforma(id,nombre) VALUES (37,'Nintendo GameCube');
INSERT INTO plataforma(id,nombre) VALUES (38,'SG-1000');
INSERT INTO plataforma(id,nombre) VALUES (39,'Namco Galaga');
INSERT INTO plataforma(id,nombre) VALUES (40,'PlayStation');
INSERT INTO plataforma(id,nombre) VALUES (41,'Nintendo 3DS');
INSERT INTO plataforma(id,nombre) VALUES (42,'PC Engine');
INSERT INTO plataforma(id,nombre) VALUES (43,'Nintendo 64');
INSERT INTO plataforma(id,nombre) VALUES (44,'Xbox One');
INSERT INTO plataforma(id,nombre) VALUES (45,'Adobe Flash Player');
INSERT INTO plataforma(id,nombre) VALUES (46,'Familia Atari de 8 bits');
INSERT INTO plataforma(id,nombre) VALUES (47,'Windows Phone');
INSERT INTO plataforma(id,nombre) VALUES (48,'SuperGrafx');
INSERT INTO plataforma(id,nombre) VALUES (49,'Neo-Geo');
INSERT INTO plataforma(id,nombre) VALUES (50,'Game Boy');
INSERT INTO plataforma(id,nombre) VALUES (51,'Game Boy Color');
INSERT INTO plataforma(id,nombre) VALUES (52,'Atari 5200');
INSERT INTO plataforma(id,nombre) VALUES (53,'NEC PC-8801');
INSERT INTO plataforma(id,nombre) VALUES (54,'navegador web');
INSERT INTO plataforma(id,nombre) VALUES (55,'Sega Dreamcast');
INSERT INTO plataforma(id,nombre) VALUES (56,'Windows 9x');
INSERT INTO plataforma(id,nombre) VALUES (57,'Sega Saturn');
INSERT INTO plataforma(id,nombre) VALUES (58,'PlayStation Network');
INSERT INTO plataforma(id,nombre) VALUES (59,'Xbox Live Arcade');
INSERT INTO plataforma(id,nombre) VALUES (60,'Consola Virtual');
INSERT INTO plataforma(id,nombre) VALUES (61,'Neo Geo CD');
INSERT INTO plataforma(id,nombre) VALUES (62,'arkádní videohra');
INSERT INTO plataforma(id,nombre) VALUES (63,'Sega Game Gear');
INSERT INTO plataforma(id,nombre) VALUES (64,'Adobe Flash Professional');
INSERT INTO plataforma(id,nombre) VALUES (65,'Commodore VIC-20');
INSERT INTO plataforma(id,nombre) VALUES (66,'Apple IIGS');
INSERT INTO plataforma(id,nombre) VALUES (67,'Placa de arcade');
INSERT INTO plataforma(id,nombre) VALUES (68,'Macintosh');
INSERT INTO plataforma(id,nombre) VALUES (69,'teléfono móvil');
INSERT INTO plataforma(id,nombre) VALUES (70,'N-Gage');
INSERT INTO plataforma(id,nombre) VALUES (71,'borne d''arcade');
INSERT INTO plataforma(id,nombre) VALUES (72,'Steam');
INSERT INTO plataforma(id,nombre) VALUES (73,'Open Graph Protocol');
INSERT INTO plataforma(id,nombre) VALUES (74,'Nintendo iQue');
INSERT INTO plataforma(id,nombre) VALUES (75,'Namco System 11');
INSERT INTO plataforma(id,nombre) VALUES (76,'multiplataforma');
INSERT INTO plataforma(id,nombre) VALUES (77,'Compatible IBM PC');
INSERT INTO plataforma(id,nombre) VALUES (78,'WonderSwan');
INSERT INTO plataforma(id,nombre) VALUES (79,'Sega Master System');
INSERT INTO plataforma(id,nombre) VALUES (80,'MSX2');
INSERT INTO plataforma(id,nombre) VALUES (81,'Neo Geo Pocket Color');
INSERT INTO plataforma(id,nombre) VALUES (82,'computadora personal');
INSERT INTO plataforma(id,nombre) VALUES (83,'Commodore Amiga 1200');
INSERT INTO plataforma(id,nombre) VALUES (84,'CD-TV');
INSERT INTO plataforma(id,nombre) VALUES (85,'MS-DOS');
INSERT INTO plataforma(id,nombre) VALUES (86,'Game & Watch');
INSERT INTO plataforma(id,nombre) VALUES (87,'Barcode Battler');
INSERT INTO plataforma(id,nombre) VALUES (88,'Atari Lynx');
INSERT INTO plataforma(id,nombre) VALUES (89,'Máquina virtual Java');
INSERT INTO plataforma(id,nombre) VALUES (90,'Flash');
INSERT INTO plataforma(id,nombre) VALUES (91,'Computadora');
INSERT INTO plataforma(id,nombre) VALUES (92,'PC-FX');
INSERT INTO plataforma(id,nombre) VALUES (93,'New Nintendo 3DS');
INSERT INTO plataforma(id,nombre) VALUES (94,'Ouya');
INSERT INTO plataforma(id,nombre) VALUES (95,'Amstrad PCW');
INSERT INTO plataforma(id,nombre) VALUES (96,'WiiWare');
INSERT INTO plataforma(id,nombre) VALUES (97,'BlackBerry');
INSERT INTO plataforma(id,nombre) VALUES (98,'Nvidia Shield');
INSERT INTO plataforma(id,nombre) VALUES (99,'Vectrex');
INSERT INTO plataforma(id,nombre) VALUES (100,'PlayStation Now');
INSERT INTO plataforma(id,nombre) VALUES (101,'Anexo:Videojuegos lanzados a través de DSiWare');
INSERT INTO plataforma(id,nombre) VALUES (102,'AmigaOS');
INSERT INTO plataforma(id,nombre) VALUES (103,'AmigaCD32');
INSERT INTO plataforma(id,nombre) VALUES (104,'Acorn Electron');
INSERT INTO plataforma(id,nombre) VALUES (105,'iPhone');
INSERT INTO plataforma(id,nombre) VALUES (106,'TRS-80');
INSERT INTO plataforma(id,nombre) VALUES (107,'Commodore PET');
INSERT INTO plataforma(id,nombre) VALUES (108,'arcada');
INSERT INTO plataforma(id,nombre) VALUES (109,'ColecoVision');
INSERT INTO plataforma(id,nombre) VALUES (110,'FM Towns');
INSERT INTO plataforma(id,nombre) VALUES (111,'Atari Jaguar');
INSERT INTO plataforma(id,nombre) VALUES (112,'Sega Mega-CD');
INSERT INTO plataforma(id,nombre) VALUES (113,'PC');
INSERT INTO plataforma(id,nombre) VALUES (114,'iPad');
INSERT INTO plataforma(id,nombre) VALUES (115,'Computadora central');
INSERT INTO plataforma(id,nombre) VALUES (116,'Satellaview');
INSERT INTO plataforma(id,nombre) VALUES (117,'Sharp X68000');
INSERT INTO plataforma(id,nombre) VALUES (118,'Nintendo DSi');
INSERT INTO plataforma(id,nombre) VALUES (119,'NEC PC-9801');
INSERT INTO plataforma(id,nombre) VALUES (120,'Java Micro Edition');
INSERT INTO plataforma(id,nombre) VALUES (121,'Facebook');
INSERT INTO plataforma(id,nombre) VALUES (122,'IBM PC DOS');
INSERT INTO plataforma(id,nombre) VALUES (123,'Milton Bradley Microvison');
INSERT INTO plataforma(id,nombre) VALUES (124,'GNU/Linux');
INSERT INTO plataforma(id,nombre) VALUES (125,'plataforma Java');
INSERT INTO plataforma(id,nombre) VALUES (126,'Dragon 32/64');
INSERT INTO plataforma(id,nombre) VALUES (127,'Nintendo Switch');
INSERT INTO plataforma(id,nombre) VALUES (128,'IBM PC');
INSERT INTO plataforma(id,nombre) VALUES (129,'BBC Micro');
INSERT INTO plataforma(id,nombre) VALUES (130,'Windows 8.1');
INSERT INTO plataforma(id,nombre) VALUES (131,'Windows 10');
INSERT INTO plataforma(id,nombre) VALUES (132,'PV-1000');
INSERT INTO plataforma(id,nombre) VALUES (133,'Reproductor de DVD');
INSERT INTO plataforma(id,nombre) VALUES (134,'Namco System ES3');
INSERT INTO plataforma(id,nombre) VALUES (135,'Model 1');
INSERT INTO plataforma(id,nombre) VALUES (136,'Sega 32X');
INSERT INTO plataforma(id,nombre) VALUES (137,'Virtual Boy');
INSERT INTO plataforma(id,nombre) VALUES (138,'TvOS');
INSERT INTO plataforma(id,nombre) VALUES (139,'NeXT');
INSERT INTO plataforma(id,nombre) VALUES (140,'RISC PC');
INSERT INTO plataforma(id,nombre) VALUES (141,'SteamOS');
INSERT INTO plataforma(id,nombre) VALUES (142,'Sega Pico');
INSERT INTO plataforma(id,nombre) VALUES (143,'PC Engine Duo');
INSERT INTO plataforma(id,nombre) VALUES (144,'Windows Mobile');
INSERT INTO plataforma(id,nombre) VALUES (145,'Apple Watch');
INSERT INTO plataforma(id,nombre) VALUES (146,'CP/M');
INSERT INTO plataforma(id,nombre) VALUES (147,'Texas Instruments TI-99/4A');
INSERT INTO plataforma(id,nombre) VALUES (148,'BlackBerry OS');
INSERT INTO plataforma(id,nombre) VALUES (149,'Videojuego para móviles');
INSERT INTO plataforma(id,nombre) VALUES (150,'Sinclair ZX81');
INSERT INTO plataforma(id,nombre) VALUES (151,'Alltel');
INSERT INTO plataforma(id,nombre) VALUES (152,'Bada');
INSERT INTO plataforma(id,nombre) VALUES (153,'HP webOS');
INSERT INTO plataforma(id,nombre) VALUES (154,'Symbian OS');
INSERT INTO plataforma(id,nombre) VALUES (155,'OnLive');
INSERT INTO plataforma(id,nombre) VALUES (156,'Commodore 128');
INSERT INTO plataforma(id,nombre) VALUES (157,'Xbox Live');
INSERT INTO plataforma(id,nombre) VALUES (158,'Kinect');
INSERT INTO plataforma(id,nombre) VALUES (159,'Fire TV Stick');
INSERT INTO plataforma(id,nombre) VALUES (160,'Windows Phone 8');
INSERT INTO plataforma(id,nombre) VALUES (161,'Intellivision');
INSERT INTO plataforma(id,nombre) VALUES (162,'Nintendo 64DD');
INSERT INTO plataforma(id,nombre) VALUES (163,'Pocket PC');
INSERT INTO plataforma(id,nombre) VALUES (164,'Palm OS');
INSERT INTO plataforma(id,nombre) VALUES (165,'Online y offline');
INSERT INTO plataforma(id,nombre) VALUES (166,'Commodore Amiga 500');
INSERT INTO plataforma(id,nombre) VALUES (167,'CPS-2');
INSERT INTO plataforma(id,nombre) VALUES (168,'FM-7');
INSERT INTO plataforma(id,nombre) VALUES (169,'salón recreativo');
INSERT INTO plataforma(id,nombre) VALUES (170,'Hulotte');
INSERT INTO plataforma(id,nombre) VALUES (171,'PlayStation 2 Expansion Bay');
INSERT INTO plataforma(id,nombre) VALUES (172,'CPS-1');
INSERT INTO plataforma(id,nombre) VALUES (173,'Nintendo Super System');
INSERT INTO plataforma(id,nombre) VALUES (174,'Sharp X1');
INSERT INTO plataforma(id,nombre) VALUES (175,'IBM Personal Computer XT');
INSERT INTO plataforma(id,nombre) VALUES (176,'Apple IIe');
INSERT INTO plataforma(id,nombre) VALUES (177,'Línea Game Boy');
INSERT INTO plataforma(id,nombre) VALUES (178,'Máquina-Z');
INSERT INTO plataforma(id,nombre) VALUES (179,'Applet Java');
INSERT INTO plataforma(id,nombre) VALUES (180,'En línea');
INSERT INTO plataforma(id,nombre) VALUES (181,'FOMA');
INSERT INTO plataforma(id,nombre) VALUES (182,'Gizmondo');
INSERT INTO plataforma(id,nombre) VALUES (183,'Kaypro');
INSERT INTO plataforma(id,nombre) VALUES (184,'Xerox Alto');
INSERT INTO plataforma(id,nombre) VALUES (185,'I-mode');
INSERT INTO plataforma(id,nombre) VALUES (186,'Apple');
INSERT INTO plataforma(id,nombre) VALUES (187,'Commodore Plus/4');
INSERT INTO plataforma(id,nombre) VALUES (188,'R-Zone');
INSERT INTO plataforma(id,nombre) VALUES (189,'TRS-80 Color Computer');
INSERT INTO plataforma(id,nombre) VALUES (190,'Sistema operativo de disco');
INSERT INTO plataforma(id,nombre) VALUES (191,'BlackBerry PlayBook');
INSERT INTO plataforma(id,nombre) VALUES (192,'BlackBerry 10');
INSERT INTO plataforma(id,nombre) VALUES (193,'Glulx');
INSERT INTO plataforma(id,nombre) VALUES (194,'Nintendo eShop');
INSERT INTO plataforma(id,nombre) VALUES (195,'Handheld TV game');
INSERT INTO plataforma(id,nombre) VALUES (196,'Multics');
INSERT INTO plataforma(id,nombre) VALUES (197,'PDP-7');
INSERT INTO plataforma(id,nombre) VALUES (198,'GCOS');
INSERT INTO plataforma(id,nombre) VALUES (199,'Windows 8');
INSERT INTO plataforma(id,nombre) VALUES (200,'Windows 7');
INSERT INTO plataforma(id,nombre) VALUES (201,'Enterprise 128');
INSERT INTO plataforma(id,nombre) VALUES (202,'Nintendo Vs.');
INSERT INTO plataforma(id,nombre) VALUES (203,'Atari');
INSERT INTO plataforma(id,nombre) VALUES (204,'Neo Geo Pocket');
INSERT INTO plataforma(id,nombre) VALUES (205,'Tandy Video Information System');
INSERT INTO plataforma(id,nombre) VALUES (206,'Mac OS 9');
INSERT INTO plataforma(id,nombre) VALUES (207,'Windows 3.1');
INSERT INTO plataforma(id,nombre) VALUES (208,'iPod');
INSERT INTO plataforma(id,nombre) VALUES (209,'Atari System');
INSERT INTO plataforma(id,nombre) VALUES (210,'EDSAC');
INSERT INTO plataforma(id,nombre) VALUES (211,'Sony Interactive Entertainment');
INSERT INTO plataforma(id,nombre) VALUES (212,'Philips');
INSERT INTO plataforma(id,nombre) VALUES (213,'Super A''Can');
INSERT INTO plataforma(id,nombre) VALUES (214,'Super CD-ROM2');
INSERT INTO plataforma(id,nombre) VALUES (215,'Magnavox Odyssey²');
INSERT INTO plataforma(id,nombre) VALUES (216,'NEC PC-6001');
INSERT INTO plataforma(id,nombre) VALUES (217,'OLPC XO-1');
INSERT INTO plataforma(id,nombre) VALUES (218,'Commodore International');
INSERT INTO plataforma(id,nombre) VALUES (219,'DESQview');
INSERT INTO plataforma(id,nombre) VALUES (220,'Apple Pippin');
INSERT INTO plataforma(id,nombre) VALUES (221,'Zeebo');
INSERT INTO plataforma(id,nombre) VALUES (222,'Google Chrome');
INSERT INTO plataforma(id,nombre) VALUES (223,'HTML 5');
INSERT INTO plataforma(id,nombre) VALUES (224,'Sega Mega-Tech');
INSERT INTO plataforma(id,nombre) VALUES (225,'Computadora analógica');
INSERT INTO plataforma(id,nombre) VALUES (226,'Windows 10 Mobile');
INSERT INTO plataforma(id,nombre) VALUES (227,'Thomson TO7');
INSERT INTO plataforma(id,nombre) VALUES (228,'Thomson MO5');
INSERT INTO plataforma(id,nombre) VALUES (229,'Sharp MZ-80K');
INSERT INTO plataforma(id,nombre) VALUES (230,'iPod touch');
INSERT INTO plataforma(id,nombre) VALUES (231,'Q7446154');
INSERT INTO plataforma(id,nombre) VALUES (232,'Google Chrome OS');
INSERT INTO plataforma(id,nombre) VALUES (233,'Kindle Fire HD');
INSERT INTO plataforma(id,nombre) VALUES (234,'Model 3');