insert into videojuego (id, titulo, puntnMedia) values (1, 'nisl ut', 8);
insert into videojuego (id, titulo, puntnMedia) values (2, 'quis lectus', 9);
insert into videojuego (id, titulo, puntnMedia) values (3, 'pulvinar lobortis est', 10);
insert into videojuego (id, titulo, puntnMedia) values (4, 'diam neque', 10);
insert into videojuego (id, titulo, puntnMedia) values (5, 'ullamcorper', 1);
insert into videojuego (id, titulo, puntnMedia) values (6, 'mi pede malesuada', 6);
insert into videojuego (id, titulo, puntnMedia) values (7, 'sit', 1);
insert into videojuego (id, titulo, puntnMedia) values (8, 'vestibulum', 7);
insert into videojuego (id, titulo, puntnMedia) values (9, 'dictumst', 10);
insert into videojuego (id, titulo, puntnMedia) values (10, 'cubilia curae donec', 1);
insert into videojuego (id, titulo, puntnMedia) values (11, 'in', 1);
insert into videojuego (id, titulo, puntnMedia) values (12, 'amet', 2);
insert into videojuego (id, titulo, puntnMedia) values (13, 'aliquam non', 7);
insert into videojuego (id, titulo, puntnMedia) values (14, 'quis augue luctus', 5);
insert into videojuego (id, titulo, puntnMedia) values (15, 'vel dapibus', 5);
insert into videojuego (id, titulo, puntnMedia) values (16, 'aliquam quis turpis', 9);
insert into videojuego (id, titulo, puntnMedia) values (17, 'egestas metus aenean', 8);
insert into videojuego (id, titulo, puntnMedia) values (18, 'potenti', 5);
insert into videojuego (id, titulo, puntnMedia) values (19, 'pellentesque ultrices phasellus', 1);
insert into videojuego (id, titulo, puntnMedia) values (20, 'aenean', 6);
insert into videojuego (id, titulo, puntnMedia) values (21, 'orci', 1);
insert into videojuego (id, titulo, puntnMedia) values (22, 'a libero', 1);
insert into videojuego (id, titulo, puntnMedia) values (23, 'curabitur', 5);
insert into videojuego (id, titulo, puntnMedia) values (24, 'vestibulum sit amet', 9);
insert into videojuego (id, titulo, puntnMedia) values (25, 'sit amet', 1);
insert into videojuego (id, titulo, puntnMedia) values (26, 'ante', 4);
insert into videojuego (id, titulo, puntnMedia) values (27, 'tellus', 9);
insert into videojuego (id, titulo, puntnMedia) values (28, 'justo lacinia eget', 3);
insert into videojuego (id, titulo, puntnMedia) values (29, 'eu sapien cursus', 4);
insert into videojuego (id, titulo, puntnMedia) values (30, 'in lacus curabitur', 7);
insert into videojuego (id, titulo, puntnMedia) values (31, 'suspendisse', 6);
insert into videojuego (id, titulo, puntnMedia) values (32, 'adipiscing', 7);
insert into videojuego (id, titulo, puntnMedia) values (33, 'interdum in', 8);
insert into videojuego (id, titulo, puntnMedia) values (34, 'rhoncus', 9);
insert into videojuego (id, titulo, puntnMedia) values (35, 'nulla', 5);
insert into videojuego (id, titulo, puntnMedia) values (36, 'sit', 4);
insert into videojuego (id, titulo, puntnMedia) values (37, 'leo maecenas', 6);
insert into videojuego (id, titulo, puntnMedia) values (38, 'non velit', 9);
insert into videojuego (id, titulo, puntnMedia) values (39, 'ultrices libero', 6);
insert into videojuego (id, titulo, puntnMedia) values (40, 'condimentum neque', 5);
insert into videojuego (id, titulo, puntnMedia) values (41, 'cubilia', 10);
insert into videojuego (id, titulo, puntnMedia) values (42, 'sit amet consectetuer', 5);
insert into videojuego (id, titulo, puntnMedia) values (43, 'amet', 8);
insert into videojuego (id, titulo, puntnMedia) values (44, 'luctus', 3);
insert into videojuego (id, titulo, puntnMedia) values (45, 'rhoncus aliquam', 10);
insert into videojuego (id, titulo, puntnMedia) values (46, 'ultricies eu nibh', 7);
insert into videojuego (id, titulo, puntnMedia) values (47, 'volutpat in', 2);
insert into videojuego (id, titulo, puntnMedia) values (48, 'pulvinar', 7);
insert into videojuego (id, titulo, puntnMedia) values (49, 'nullam varius nulla', 7);
insert into videojuego (id, titulo, puntnMedia) values (50, 'fermentum donec', 8);
insert into videojuego (id, titulo, puntnMedia) values (51, 'consequat ut', 2);
insert into videojuego (id, titulo, puntnMedia) values (52, 'amet nulla', 8);
insert into videojuego (id, titulo, puntnMedia) values (53, 'eu mi nulla', 5);
insert into videojuego (id, titulo, puntnMedia) values (54, 'in felis eu', 2);
insert into videojuego (id, titulo, puntnMedia) values (55, 'justo lacinia', 1);
insert into videojuego (id, titulo, puntnMedia) values (56, 'pellentesque ultrices phasellus', 3);
insert into videojuego (id, titulo, puntnMedia) values (57, 'sit amet justo', 9);
insert into videojuego (id, titulo, puntnMedia) values (58, 'est risus auctor', 3);
insert into videojuego (id, titulo, puntnMedia) values (59, 'leo odio', 8);
insert into videojuego (id, titulo, puntnMedia) values (60, 'non', 7);
insert into videojuego (id, titulo, puntnMedia) values (61, 'sapien', 1);
insert into videojuego (id, titulo, puntnMedia) values (62, 'dui', 3);
insert into videojuego (id, titulo, puntnMedia) values (63, 'nec', 8);
insert into videojuego (id, titulo, puntnMedia) values (64, 'amet consectetuer adipiscing', 4);
insert into videojuego (id, titulo, puntnMedia) values (65, 'feugiat', 10);
insert into videojuego (id, titulo, puntnMedia) values (66, 'congue diam id', 10);
insert into videojuego (id, titulo, puntnMedia) values (67, 'a pede posuere', 8);
insert into videojuego (id, titulo, puntnMedia) values (68, 'amet', 8);
insert into videojuego (id, titulo, puntnMedia) values (69, 'ultrices', 2);
insert into videojuego (id, titulo, puntnMedia) values (70, 'vulputate vitae nisl', 8);
insert into videojuego (id, titulo, puntnMedia) values (71, 'sed', 8);
insert into videojuego (id, titulo, puntnMedia) values (72, 'augue', 4);
insert into videojuego (id, titulo, puntnMedia) values (73, 'nibh in', 2);
insert into videojuego (id, titulo, puntnMedia) values (74, 'sit amet', 8);
insert into videojuego (id, titulo, puntnMedia) values (75, 'eros', 6);
insert into videojuego (id, titulo, puntnMedia) values (76, 'justo in blandit', 9);
insert into videojuego (id, titulo, puntnMedia) values (77, 'metus', 10);
insert into videojuego (id, titulo, puntnMedia) values (78, 'erat eros viverra', 4);
insert into videojuego (id, titulo, puntnMedia) values (79, 'in', 6);
insert into videojuego (id, titulo, puntnMedia) values (80, 'sed nisl', 9);
insert into videojuego (id, titulo, puntnMedia) values (81, 'massa id', 8);
insert into videojuego (id, titulo, puntnMedia) values (82, 'sit', 1);
insert into videojuego (id, titulo, puntnMedia) values (83, 'egestas metus', 6);
insert into videojuego (id, titulo, puntnMedia) values (84, 'morbi sem mauris', 7);
insert into videojuego (id, titulo, puntnMedia) values (85, 'quisque', 8);
insert into videojuego (id, titulo, puntnMedia) values (86, 'eros elementum pellentesque', 8);
insert into videojuego (id, titulo, puntnMedia) values (87, 'orci mauris lacinia', 4);
insert into videojuego (id, titulo, puntnMedia) values (88, 'elementum eu', 10);
insert into videojuego (id, titulo, puntnMedia) values (89, 'non sodales sed', 1);
insert into videojuego (id, titulo, puntnMedia) values (90, 'ante', 4);
insert into videojuego (id, titulo, puntnMedia) values (91, 'est donec', 1);
insert into videojuego (id, titulo, puntnMedia) values (92, 'quis odio', 3);
insert into videojuego (id, titulo, puntnMedia) values (93, 'ipsum', 2);
insert into videojuego (id, titulo, puntnMedia) values (94, 'posuere felis sed', 6);
insert into videojuego (id, titulo, puntnMedia) values (95, 'in faucibus', 8);
insert into videojuego (id, titulo, puntnMedia) values (96, 'sed ante vivamus', 3);
insert into videojuego (id, titulo, puntnMedia) values (97, 'sit', 8);
insert into videojuego (id, titulo, puntnMedia) values (98, 'a odio', 10);
insert into videojuego (id, titulo, puntnMedia) values (99, 'proin', 5);
insert into videojuego (id, titulo, puntnMedia) values (100, 'mattis egestas metus', 10);
